# 使用官方的Python镜像作为基础镜像
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel

# 设置工作目录
WORKDIR /app

# 将本地文件添加到镜像中
ADD . /app

# 安装应用所需的依赖
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London
RUN apt-get update
RUN apt-get install vim -y
RUN apt-get install -y iputils-ping
RUN apt-get -y install gcc
RUN apt-get -y install g++
RUN apt-get -y install tk
RUN apt-get -y install libglib2.0-0 libsm6 libxrender1 libxext6

RUN pip install --trusted-host pypi.python.org -r requirements.txt

# 在容器启动时运行python app.py
# CMD ["python", "app.py"]
CMD ["/bin/bash"]